import React from "react";

const Testimonials = () => {
  const testimonials = [
    {
      name: "John Doe",
      comment:
        "This tool is incredible for quickly finding bugs and improving code quality. Highly recommend!",
      role: "Software Developer",
    },
    {
      name: "Jane Smith",
      comment:
        "It helped me refactor my entire codebase in no time. A must-have tool for every developer.",
      role: "Senior Engineer",
    },
    {
      name: "Mark Johnson",
      comment:
        "The unit tests generated by this tool are spot on. Saved me a lot of time and effort.",
      role: "Backend Developer",
    },
    {
      name: "Emily Davis",
      comment:
        "I love how the tool not only reviews but also suggests improvements. It makes me a better coder.",
      role: "Frontend Developer",
    },
    {
      name: "David Lee",
      comment:
        "The algorithm explanation feature is superb! Helps me understand complex code easily.",
      role: "Data Scientist",
    },
  ];

  return (
    <div className="px-6 py-6 bg-transparent cursor-pointer flex flex-col gap-10">
      <h1 className="text-7xl font-bold pt-5 text-center  text-white">
        What Our Users Says
      </h1>

      <div className=" max-w-full xl:max-w-5xl mx-auto p-8">
        <div className="flex space-x-6 overflow-x-auto pb-6">
          {testimonials.map((testimonial, index) => (
            <div
              key={index}
              className="bg-neutral-950 border border-[#535353] hover:scale-105 transition-all duration-500  p-6 rounded-lg  
             drop-shadow-md  w-full sm:w-80 flex-shrink-0 text-white"
            >
              <p className="italic text-lg mb-4">"{testimonial.comment}"</p>
              <p className="font-bold text-purple-500">{testimonial.name}</p>
              <p className="text-sm text-gray-500">{testimonial.role}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Testimonials;
